version: "3.8"
name: lab3

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    expose:
      - 80
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: "uvicorn main:app --host 0.0.0.0 --port 80"


  status_service:
    build:
      context: ./status_service
      dockerfile: Dockerfile
    depends_on:
        rabbitmq:
          condition: service_healthy
    deploy:
      replicas: 2
    command: "python main.py"


  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "mydbname", "-U", "user"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data_lab3:/var/lib/postgresql/data
  

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data_lab3:
